### ISSUE TITLE
Roadmap / Идеи и планы

### ISSUE THREAD

**Issue by DartPower** [dpteam/DarkSpace#2]
Идея пока что только в стадии зарождения, но вот какие мысли по поводу игры:

Суть: Простая текстовая стратегия на космическую тематику с элементами юмора.
Рейтинг 18+, сразу говорю 🤣 
Будет по смыслу ещё напоминать E.L.I.T.E.

Ближайшие планы:
 - [x] Простейшее ядро клиента
 - [x] Логирование 
 - [x] Чтение конфигурации из INI-файла 
 - [x] Запись конфигурации в INI-файл 
 - [ ] Додумать основную идею и закрепить
 - [x] Создание генератора вселенной и сохраненки.
   - [x] Сделать запись и чтение основных метаданных, данные о корабле, деньгах и главном герое...
   - [x] Сделать процедурную генерацию корабля (описание и характеристики) по паттернам.
   - [x] Сделать процедурную генерацию космических тел (описание и характеристики) по паттернам.
      - [x] Черные дыры
      - [x] Звезды
      - [x] Планеты
      - [x] Расы, города и инфраструктура с экономикой, религией и сообществом. (Да это жёстко)

Основные планы: 
 - [ ] Реализация всех перечислений. 
   - [ ] Создать простую систему валюты.
   - [ ] Создать простую систему элементов. 
Т.к. логика всех ресурсов игры будет основана по идее "алхимии", можно будет написать рецепторный сценарий. Для автоматического создания уникальных ресурсов. Можно будет сделать генерацию имен из двух названий элементов.
   - [ ] Создать простую систему типов галактик.
Пока что планирую сделать 256 галактик (отсылка к NMS)
   - [ ] Создать простую систему фракций (кланов/банд). Пока что не определился с названиями.
   - [ ] Создать простую систему предметов. Список будет пополнятся, пока что мало чего есть.
 - [ ] Создание клиент-серверной архитектуры
   - [ ] Реализовать создание сервера и синхронизации данных между клиентом и сервером

Будущие планы:
 - [ ] Написать полноценный сюжет
 - [ ] Логирование перенести в log4net
 - [ ] Конфиги перенести в Json
 - [ ] Реализовать более умную систему сохранений
